# Generated by Django 4.2.20 on 2025-03-31 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scriptly', '0002_alter_scriptversion_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scriptversion',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_versions', to=settings.AUTH_USER_MODEL),
        ),
    ]
