# Generated by Django 4.2.20 on 2025-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptly', '0003_alter_scriptversion_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptlyjob',
            name='celery_id',
        ),
        migrations.AlterField(
            model_name='scriptlyjob',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('deleted', 'Deleted'), ('failed', 'Failed'), ('error', 'Error'), ('running', 'Running'), ('submitted', 'Submitted')], default='submitted', max_length=255),
        ),
    ]
