# Generated by Django 4.2.20 on 2025-05-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptly', '0004_remove_scriptlyjob_celery_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptlyjob',
            name='output_files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
