name: Deploy-To-Docker

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Build image
        run: |
          docker build -f docker/Dockerfile -t scriptly/scriptly:latest .
          docker tag scriptly/scriptly:latest scriptly/scriptly:${GITHUB_REF#refs/tags/}
      - name: Upload image to Dockerhub
        env:
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker login --username scriptlyservice -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          docker push scriptly/scriptly:latest
          docker push scriptly/scriptly:${GITHUB_REF#refs/tags/}
